name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set working directory
        run: |
          cd ${{ inputs.projectPath }}
          ls  # Optional: Display the directory contents for verification

      - name: Build whole project
        run: dotnet build ${{ inputs.solutionPath }}

      - name: Build and run tests
        run: dotnet test ${{ inputs.projectPath }}
