name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build whole project
        run: dotnet build ${{ inputs.solutionPath }}
        
      - name: Build and run tests
        run: dotnet test ${{ inputs.projectPath }}
